[versions]
compose = "1.2.1"
# Last version to support Kotlin 1.7.20
# https://developer.android.com/jetpack/androidx/releases/compose-kotlin
composecompiler = "1.3.1"
composesnapshot = "-" # a single character = no snapshot

agp = "8.0.0-alpha05"

ktlint = "0.45.2"
kotlin = "1.7.10"
coroutines = "1.5.2"

androidxtest = "1.4.0"
androidxnavigation = "2.5.1"

[plugins]
metalavaGradle = { id = "me.tylerbwong.gradle.metalava", version = "0.2.3" }
jetbrainsCompose = { id = "org.jetbrains.compose", version = "1.2.0" }

[libraries]
compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
compose-material-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material-iconsext = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-animation-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }

android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradleMavenPublishPlugin = "com.vanniktech:gradle-maven-publish-plugin:0.18.0"

atomicfu-gradlePlugin = "org.jetbrains.kotlinx:atomicfu-gradle-plugin:0.18.4"

coil = "io.coil-kt:coil-compose:1.4.0"

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

dokka = "org.jetbrains.dokka:dokka-gradle-plugin:1.7.10"

androidx-core = "androidx.core:core-ktx:1.8.0"
androidx-activity-compose = "androidx.activity:activity-compose:1.5.1"

androidx-test-core = { module = "androidx.test:core-ktx", version.ref = "androidxtest" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxtest" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxtest" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidxtest" }

junit = "junit:junit:4.13"
truth = "com.google.truth:truth:1.1.2"
robolectric = "org.robolectric:robolectric:4.8.2"
